name: kimchi-CI
on: ["push"]

env:
  VM_NAME: ubuntu-${{ github.sha }}
  ZONE: us-central1-a
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  WOK_DIR: wok
  KIMCHI_DIR: wok/src/wok/plugins/kimchi/

jobs:
  run-kimchi-tests:
    runs-on: ubuntu-latest
    steps:

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
            version: '270.0.0'
            service_account_email: ${{ secrets.GCP_SA_EMAIL }}
            service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: gcloud config set project $PROJECT_ID

      - uses: actions/checkout@v2-beta
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # If you wish to fail your job when the Quality Gate is red, uncomment the
      # following lines. This would typically be used to fail a deployment.
      # We do not recommend to use this in a pull request. Prefer using pull request
      # decoration instead.
      # - uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: create instance
        run: bash .github/scripts/setup_instance.sh $VM_NAME ubuntu-os-cloud ubuntu-1804-lts
        shell: bash

      - name: checkout repos
        run: |
          gcloud compute ssh $VM_NAME --zone=$ZONE --command "git clone https://github.com/kimchi-project/wok"
          gcloud compute ssh $VM_NAME --zone=$ZONE --command "git clone https://github.com/$GITHUB_REPOSITORY $KIMCHI_DIR"
          gcloud compute ssh $VM_NAME --zone=$ZONE --command "cd $KIMCHI_DIR; git checkout $GITHUB_SHA"
        shell: bash

      - name: setup wok deps
        run: |
          gcloud compute ssh $VM_NAME --zone=$ZONE --command "cd $WOK_DIR; bash .github/scripts/setup_wok_ubuntu.sh"
        shell: bash

      - name: setup kimchi deps
        run: gcloud compute ssh $VM_NAME --zone=$ZONE --command "cd $KIMCHI_DIR; bash .github/scripts/setup_kimchi_ubuntu.sh"
        shell: bash

      - name: run tests
        run: gcloud compute ssh $VM_NAME --zone=$ZONE --command "cd $KIMCHI_DIR; sudo make check-local; sudo make check"
        shell: bash

      - name: Cleanup instance
        if: always()
        run: |
          gcloud compute instances delete ${VM_NAME} --delete-disks=all --zone=$ZONE -q || true
          gcloud compute images delete ${VM_NAME}-image -q || true
          gcloud compute disks delete ${VM_NAME}-disk --zone=$ZONE -q || true
        shell: bash
